// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aafvhroqhrnacutprujn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhZnZocm9xaHJuYWN1dHBydWpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MjIzODcsImV4cCI6MjA3MDM5ODM4N30.45Ub5rrtyd6NEnq6-Jz9Rtst12eTX3I0oPIAJ66t7CI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Helper function for auth with correct redirect
export const signInWithRedirect = async (email: string, password: string) => {
  return await supabase.auth.signInWithPassword({
    email,
    password,
  });
};

export const signUpWithRedirect = async (email: string, password: string, options?: Record<string, unknown>) => {
  return await supabase.auth.signUp({
    email,
    password,
    options: {
      ...options,
      emailRedirectTo: `${window.location.origin}/auth/callback`,
    }
  });
};